os:
  - linux
  - osx

osx_image: xcode10.1

sudo: required

dist: xenial

language: cpp

addons:
  apt:
    sources:
    - xenial
    - sourceline: 'deb http://archive.ubuntu.com/ubuntu xenial main'
    packages:
    - openssl
    - libssl-dev
    - build-essential
    - cmake
  homebrew:
    packages:
    - openssl
    - cmake
    - libtool

script:
  - ./build.sh


